# Generated by Django 5.0.4 on 2024-05-04 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hotel_id", models.CharField(max_length=100)),
                ("personal_name", models.CharField(max_length=100)),
                ("personal_mobile", models.CharField(max_length=100)),
                ("total", models.CharField(max_length=100)),
                ("personal_nin", models.CharField(default="", max_length=100)),
                ("number_of_adults", models.IntegerField(default="")),
                ("number_of_children", models.IntegerField(default="")),
                ("number_of_rooms", models.IntegerField(default="")),
            ],
        ),
        migrations.CreateModel(
            name="Hotel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hotel_id", models.IntegerField()),
                ("hotel_name", models.CharField(max_length=50)),
                ("hotel_photo", models.ImageField(upload_to="hotel_images")),
            ],
        ),
    ]
