# Generated by Django 5.0.4 on 2024-05-04 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="number_of_adults",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="booking",
            name="number_of_children",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="booking",
            name="number_of_rooms",
            field=models.CharField(default="", max_length=100),
        ),
    ]
