# Generated by Django 5.0.4 on 2024-05-04 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0002_alter_booking_number_of_adults_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="hotel_id",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="booking",
            name="personal_mobile",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="booking",
            name="personal_name",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="booking",
            name="total",
            field=models.CharField(default="", max_length=100),
        ),
    ]
