# Generated by Django 4.2.11 on 2024-05-08 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_featureddestination'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FeaturedDestination',
        ),
    ]
