# Generated by Django 4.2.11 on 2024-05-09 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_featureddestination'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hm_id', models.CharField(max_length=230)),
                ('hm_image', models.ImageField(upload_to='hm_images')),
            ],
        ),
    ]
