# Generated by Django 4.2.11 on 2024-05-07 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_featureddestination'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FeaturedDestination',
        ),
    ]
