# Generated by Django 4.2.13 on 2024-05-08 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_featureddestination'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FeaturedDestination',
        ),
    ]
