# Generated by Django 4.2.11 on 2024-05-14 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0002_rename_cardholder_payment_cardholder_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='services',
            new_name='number_of_rooms',
        ),
    ]
