# Generated by Django 4.2.11 on 2024-04-18 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemContent', models.CharField(max_length=30)),
                ('itemButton', models.CharField(max_length=30)),
            ],
        ),
    ]
