# Generated by Django 4.2.11 on 2024-05-03 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trips',
            old_name='itemButton',
            new_name='trip_id',
        ),
        migrations.RenameField(
            model_name='trips',
            old_name='itemContent',
            new_name='trip_text',
        ),
        migrations.AddField(
            model_name='trips',
            name='trip_image',
            field=models.ImageField(default='none', upload_to='trip_images'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trips',
            name='trip_tittle',
            field=models.CharField(default='none', max_length=30),
            preserve_default=False,
        ),
    ]
