# Generated by Django 4.2.11 on 2024-05-03 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_rename_trips_trip'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_id', models.CharField(max_length=50)),
                ('photo', models.ImageField(upload_to='linked_images')),
            ],
        ),
    ]
