# Generated by Django 4.2.11 on 2024-05-13 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0005_trip_trip_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='trip_text',
            field=models.CharField(max_length=130),
        ),
        migrations.AlterField(
            model_name='trip',
            name='trip_tittle',
            field=models.CharField(max_length=230),
        ),
    ]
