# Generated by Django 4.2.11 on 2024-05-13 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0006_alter_trip_trip_text_alter_trip_trip_tittle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='trip_text',
            field=models.CharField(max_length=730),
        ),
        migrations.AlterField(
            model_name='trip',
            name='trip_tittle',
            field=models.CharField(max_length=730),
        ),
    ]
